name: IP-a2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - imageio=2.9.0
  - matplotlib=3.3.4
  - numpy=1.21.2
  - pillow=9.0.0
  - pytorch=1.10.1
  - scikit-image=0.18.1
  - pip:
    - opencv-python==4.6.0.66
