# config.yaml

# Data parameters
data:
  train_path: "/path/to/train/data"
  val_path: "/path/to/val/data"
  input_size: [TO_BE_SET, TO_BE_SET]  # [height, width]
  batch_size: TO_BE_SET

# Model parameters
model:
  name: "PortraitNet"

# Training parameters
training:
  epochs: TO_BE_SET
  lr: TO_BE_SET  # learning rate

# Loss function
loss:
  name: TO_BE_SET

# Optimizer
optimizer:
  name: "Adam"

# Output
output:
  checkpoint_dir: "./checkpoints"

# Hardware
device: "cuda"